version: '3.7'
services:
  app:
    container_name: docker-landchain
    restart: always
    build: .
    ports:
      - '80:80'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
